version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run build
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-eu-west-2-803917972218 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
