version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run build
      - aws cloudformation package --template-file samTemplate.yaml --output-template-file outputSamTemplate.yaml --s3-bucket getquotesdeploymentstore
      - aws cloudformation deploy --template-file outputSamTemplate.yaml --stack-name readquotes-cloudformation-stack --capabilities CAPABILITY_NAMED_IAM --debug
artifacts:
  discard_paths: yes
  type: zip
  files:
    - ./*
